name: "Hello Actions"
on:
  push:
    branches: [ "tonnytg-patch-1" ]
  pull_request:
    branches: [ "main" ]
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
